// Build-time texture atlas composer.
//
// Reads block textures from assets/textures/*.png, tiles them into a single
// PNG atlas, emits Rust constants for tile indices and atlas dimensions.
// Each source texture is resampled to fixed 16x16 (MC block-face size).

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

const TILE: u32 = 16;

/// snake_case -> CamelCase (e.g. "grass_top" -> "GrassTop").
fn to_camel(s: &str) -> String {
    s.split('_').map(|p| {
        let mut chars = p.chars();
        match chars.next() {
            Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
            None => String::new(),
        }
    }).collect()
}

// (name, file). Order defines tile index in atlas (stable for shader uv math).
const TILES: &[(&str, &str)] = &[
    ("grass_top", "grass_block_top.png"),
    ("grass_side", "grass_block_side.png"),
    ("grass_snow", "grass_block_snow.png"),
    ("dirt", "dirt.png"),
    ("stone", "stone.png"),
    ("sand", "sand.png"),
    ("water", "water_still.png"),
    ("oak_log_side", "oak_log.png"),
    ("oak_log_top", "oak_log_top.png"),
    ("oak_leaves", "oak_leaves.png"),
];

fn main() {
    println!("cargo:rerun-if-changed=assets/textures");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let in_dir = manifest_dir.join("assets/textures");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let atlas_png = out_dir.join("atlas.png");
    let atlas_rs = out_dir.join("atlas_data.rs");

    let count = TILES.len() as u32;
    // Square-ish atlas. cols = ceil(sqrt(n)); rows = ceil(n/cols).
    let cols = (count as f32).sqrt().ceil() as u32;
    let rows = (count + cols - 1) / cols;
    let atlas_w = cols * TILE;
    let atlas_h = rows * TILE;

    // RGBA buffer.
    let mut buf = vec![0u8; (atlas_w * atlas_h * 4) as usize];

    let mut entries: Vec<(String, u32, u32)> = Vec::new();
    for (i, (name, file)) in TILES.iter().enumerate() {
        let path = in_dir.join(file);
        if !path.exists() {
            panic!("missing texture: {}", path.display());
        }
        // Use `image` crate to load + resize to 16x16 RGBA.
        let img = image::open(&path).unwrap_or_else(|e| {
            panic!("failed to load {}: {}", path.display(), e)
        }).to_rgba8();
        let resized = image::imageops::resize(
            &img, TILE, TILE,
            image::imageops::FilterType::Nearest,
        );
        let tile_col = i as u32 % cols;
        let tile_row = i as u32 / cols;
        let base_x = tile_col * TILE;
        let base_y = tile_row * TILE;
        for y in 0..TILE {
            for x in 0..TILE {
                let px = resized.get_pixel(x, y);
                let dst = ((base_y + y) * atlas_w + base_x + x) as usize * 4;
                buf[dst] = px.0[0];
                buf[dst + 1] = px.0[1];
                buf[dst + 2] = px.0[2];
                buf[dst + 3] = px.0[3];
            }
        }
        entries.push((name.to_string(), tile_col, tile_row));
    }

    // Write atlas PNG (used by runtime to create GPU texture).
    image::save_buffer(
        &atlas_png, &buf, atlas_w, atlas_h,
        image::ColorType::Rgba8,
    ).expect("write atlas png");

    // Write Rust source with tile indices + uv layout.
    let mut src = String::new();
    src.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    src.push_str(&format!("pub const ATLAS_W: u32 = {};\n", atlas_w));
    src.push_str(&format!("pub const ATLAS_H: u32 = {};\n", atlas_h));
    src.push_str(&format!("pub const ATLAS_COLS: u32 = {};\n", cols));
    src.push_str(&format!("pub const ATLAS_ROWS: u32 = {};\n", rows));
    src.push_str("pub const TILE: u32 = 16;\n\n");
    src.push_str("#[derive(Copy, Clone, Debug, PartialEq, Eq)]\n");
    src.push_str("pub enum Tile {\n");
    for (name, _, _) in &entries {
        let ident = to_camel(name);
        src.push_str(&format!("    {},\n", ident));
    }
    src.push_str("}\n\n");
    src.push_str("impl Tile {\n");
    src.push_str("    pub const ALL: &'static [Tile] = &[\n");
    for (name, _, _) in &entries {
        let ident = to_camel(name);
        src.push_str(&format!("        Tile::{},\n", ident));
    }
    src.push_str("    ];\n");
    src.push_str("    pub fn index(self) -> usize {\n        self as usize\n    }\n");
    src.push_str("    /// (col, row) in atlas tile grid.\n");
    src.push_str("    pub fn grid(self) -> (u32, u32) {\n        #[allow(unused)] let _ = (); match self {\n");
    for (name, col, row) in &entries {
        let ident = to_camel(name);
        src.push_str(&format!("            Tile::{} => ({}, {}),\n", ident, col, row));
    }
    src.push_str("        }\n    }\n");
    src.push_str("}\n\n");
    src.push_str(&format!("pub const TILE_COUNT: usize = {};\n", entries.len()));

    fs::write(&atlas_rs, src).expect("write atlas_data.rs");

    // Tell downstream where atlas png lives via envvar passed to tests/tests.
    println!("cargo:rustc-env=LLAMACRAFT_ATLAS_PNG={}", atlas_png.display());
    println!("cargo:rustc-env=LLAMACRAFT_ATLAS_DIR={}", out_dir.display());

    // Try to also copy atlas into web/ for inspection (best-effort).
    let _ = Command::new("cp")
        .arg(&atlas_png)
        .arg(manifest_dir.join("web/atlas.png"))
        .status();
}