pub(crate) mod bootstrap;
mod common;
mod creative;

mod bed;
mod breaking;
mod camera;
mod combat_entities;
mod drops;
mod events;
mod item_use;
mod joinprofile;
mod menu;
mod movement_claims;
mod net_pipe;
mod off_hand;
mod placement;
mod prediction;
mod remote_join;
mod replica_world;
mod replication;
mod riding;
mod scripted;
mod section_cache;
