use super::definition::ItemDef;
use super::{HeldPose, ItemTag, ItemType};

/// Default stack size for every 0.1 block-item.
const STACK: u8 = 64;

/// Hold pose for a long-handled tool (pickaxes, axes) and the bare stick: laid
/// diagonally in the hand like a swung handle, where the upright
/// [`HeldPose::DEFAULT`] would leave it lying flat. Tuned against the first-person
/// view in `render::hand::held_sprite`.
const TOOL_POSE: HeldPose = HeldPose {
    pitch: 0.0,
    yaw: -1.5,
    roll: 0.5,
};

/// Hold pose shared by the smelted ingots (iron/copper/gold): a small bar tilted
/// to read flat-on in the hand.
const INGOT_POSE: HeldPose = HeldPose {
    pitch: -0.1,
    yaw: 1.8,
    roll: -0.75,
};

pub(super) const ALL_ITEMS: &[ItemType] = &[
    ItemType::Air,
    ItemType::Grass,
    ItemType::Dirt,
    ItemType::Stone,
    ItemType::Sand,
    ItemType::Snow,
    ItemType::Water,
    ItemType::OakLog,
    ItemType::OakLeaves,
    ItemType::SpruceLog,
    ItemType::BirchLog,
    ItemType::JungleLog,
    ItemType::AcaciaLog,
    ItemType::DarkOakLog,
    ItemType::CherryLog,
    ItemType::MangroveLog,
    ItemType::SpruceLeaves,
    ItemType::BirchLeaves,
    ItemType::JungleLeaves,
    ItemType::AcaciaLeaves,
    ItemType::DarkOakLeaves,
    ItemType::MangroveLeaves,
    ItemType::CherryLeaves,
    ItemType::AzaleaLeaves,
    ItemType::RedSand,
    ItemType::Sandstone,
    ItemType::RedSandstone,
    ItemType::Terracotta,
    ItemType::WhiteTerracotta,
    ItemType::OrangeTerracotta,
    ItemType::YellowTerracotta,
    ItemType::BrownTerracotta,
    ItemType::RedTerracotta,
    ItemType::LightGrayTerracotta,
    ItemType::Podzol,
    ItemType::Mycelium,
    ItemType::CoarseDirt,
    ItemType::Gravel,
    ItemType::Clay,
    ItemType::Mud,
    ItemType::MossBlock,
    ItemType::SnowBlock,
    ItemType::PackedIce,
    ItemType::Ice,
    ItemType::Calcite,
    ItemType::Granite,
    ItemType::Diorite,
    ItemType::Andesite,
    ItemType::Tuff,
    ItemType::CoalOre,
    ItemType::IronOre,
    ItemType::CopperOre,
    ItemType::GoldOre,
    ItemType::RedstoneOre,
    ItemType::LapisOre,
    ItemType::DiamondOre,
    ItemType::EmeraldOre,
    ItemType::Pumpkin,
    ItemType::Melon,
    ItemType::Cactus,
    ItemType::ShortGrass,
    ItemType::Fern,
    ItemType::Dandelion,
    ItemType::Poppy,
    ItemType::Cornflower,
    ItemType::Allium,
    ItemType::AzureBluet,
    ItemType::OxeyeDaisy,
    ItemType::RedTulip,
    ItemType::DeadBush,
    ItemType::BrownMushroom,
    ItemType::RedMushroom,
    ItemType::Cobblestone,
    ItemType::OakPlanks,
    ItemType::SprucePlanks,
    ItemType::BirchPlanks,
    ItemType::JunglePlanks,
    ItemType::AcaciaPlanks,
    ItemType::DarkOakPlanks,
    ItemType::CherryPlanks,
    ItemType::MangrovePlanks,
    ItemType::CraftingTable,
    ItemType::Stick,
    ItemType::WoodenPickaxe,
    ItemType::StonePickaxe,
    ItemType::RawIron,
    ItemType::RawCopper,
    ItemType::Coal,
    ItemType::IronIngot,
    ItemType::CopperIngot,
    ItemType::Furnace,
    ItemType::Chest,
    ItemType::Torch,
    ItemType::Diamond,
    ItemType::LapisLazuli,
    ItemType::RawGold,
    ItemType::GoldIngot,
    ItemType::WoodenAxe,
    ItemType::StoneAxe,
    ItemType::IronAxe,
    ItemType::DiamondAxe,
    ItemType::IronPickaxe,
    ItemType::DiamondPickaxe,
    ItemType::WoodenShovel,
    ItemType::StoneShovel,
    ItemType::IronShovel,
    ItemType::DiamondShovel,
    ItemType::FurnitureWorkbench,
    ItemType::OakSapling,
    ItemType::SpruceSapling,
    ItemType::BirchSapling,
    ItemType::JungleSapling,
    ItemType::AcaciaSapling,
    ItemType::DarkOakSapling,
    ItemType::CherrySapling,
    ItemType::OakDoor,
    ItemType::SpruceDoor,
    ItemType::BirchDoor,
    ItemType::JungleDoor,
    ItemType::AcaciaDoor,
    ItemType::DarkOakDoor,
    ItemType::CherryDoor,
    ItemType::MangroveDoor,
    ItemType::RedwoodLog,
    ItemType::RedwoodLeaves,
    ItemType::RedwoodPlanks,
    ItemType::RedwoodDoor,
    ItemType::OakStairs,
    ItemType::SpruceStairs,
    ItemType::BirchStairs,
    ItemType::JungleStairs,
    ItemType::AcaciaStairs,
    ItemType::DarkOakStairs,
    ItemType::CherryStairs,
    ItemType::MangroveStairs,
    ItemType::RedwoodStairs,
    ItemType::CobblestoneStairs,
    ItemType::StoneStairs,
    ItemType::DirtStairs,
    ItemType::WoodenBucket,
    ItemType::WaterBucket,
    ItemType::Shears,
    ItemType::Wool,
    ItemType::BedFrame,
    ItemType::Bed,
];

pub(super) const ITEM_DEFS: &[ItemDef] = &[
    ItemDef {
        item: ItemType::Air,
        key: "air",
        name: "Air",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Grass,
        key: "grass_block",
        name: "Grass Block",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Dirt,
        key: "dirt",
        name: "Dirt",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Stone,
        key: "stone",
        name: "Stone",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Sand,
        key: "sand",
        name: "Sand",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Snow,
        key: "snow",
        name: "Snow",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Water,
        key: "water",
        name: "Water",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::OakLog,
        key: "oak_log",
        name: "Oak Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::OakLeaves,
        key: "oak_leaves",
        name: "Oak Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::SpruceLog,
        key: "spruce_log",
        name: "Spruce Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::BirchLog,
        key: "birch_log",
        name: "Birch Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::JungleLog,
        key: "jungle_log",
        name: "Jungle Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::AcaciaLog,
        key: "acacia_log",
        name: "Acacia Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::DarkOakLog,
        key: "dark_oak_log",
        name: "Dark Oak Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::CherryLog,
        key: "cherry_log",
        name: "Cherry Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::MangroveLog,
        key: "mangrove_log",
        name: "Mangrove Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::SpruceLeaves,
        key: "spruce_leaves",
        name: "Spruce Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BirchLeaves,
        key: "birch_leaves",
        name: "Birch Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::JungleLeaves,
        key: "jungle_leaves",
        name: "Jungle Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AcaciaLeaves,
        key: "acacia_leaves",
        name: "Acacia Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DarkOakLeaves,
        key: "dark_oak_leaves",
        name: "Dark Oak Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::MangroveLeaves,
        key: "mangrove_leaves",
        name: "Mangrove Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CherryLeaves,
        key: "cherry_leaves",
        name: "Cherry Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AzaleaLeaves,
        key: "azalea_leaves",
        name: "Azalea Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedSand,
        key: "red_sand",
        name: "Red Sand",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Sandstone,
        key: "sandstone",
        name: "Sandstone",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedSandstone,
        key: "red_sandstone",
        name: "Red Sandstone",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Terracotta,
        key: "terracotta",
        name: "Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WhiteTerracotta,
        key: "white_terracotta",
        name: "White Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::OrangeTerracotta,
        key: "orange_terracotta",
        name: "Orange Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::YellowTerracotta,
        key: "yellow_terracotta",
        name: "Yellow Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BrownTerracotta,
        key: "brown_terracotta",
        name: "Brown Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedTerracotta,
        key: "red_terracotta",
        name: "Red Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::LightGrayTerracotta,
        key: "light_gray_terracotta",
        name: "Light Gray Terracotta",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Podzol,
        key: "podzol",
        name: "Podzol",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Mycelium,
        key: "mycelium",
        name: "Mycelium",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CoarseDirt,
        key: "coarse_dirt",
        name: "Coarse Dirt",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Gravel,
        key: "gravel",
        name: "Gravel",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Clay,
        key: "clay",
        name: "Clay",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Mud,
        key: "mud",
        name: "Mud",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::MossBlock,
        key: "moss_block",
        name: "Moss Block",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::SnowBlock,
        key: "snow_block",
        name: "Snow Block",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::PackedIce,
        key: "packed_ice",
        name: "Packed Ice",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Ice,
        key: "ice",
        name: "Ice",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Calcite,
        key: "calcite",
        name: "Calcite",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Granite,
        key: "granite",
        name: "Granite",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Diorite,
        key: "diorite",
        name: "Diorite",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Andesite,
        key: "andesite",
        name: "Andesite",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Tuff,
        key: "tuff",
        name: "Tuff",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CoalOre,
        key: "coal_ore",
        name: "Coal Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::IronOre,
        key: "iron_ore",
        name: "Iron Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CopperOre,
        key: "copper_ore",
        name: "Copper Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::GoldOre,
        key: "gold_ore",
        name: "Gold Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedstoneOre,
        key: "redstone_ore",
        name: "Redstone Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::LapisOre,
        key: "lapis_ore",
        name: "Lapis Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DiamondOre,
        key: "diamond_ore",
        name: "Diamond Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::EmeraldOre,
        key: "emerald_ore",
        name: "Emerald Ore",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Pumpkin,
        key: "pumpkin",
        name: "Pumpkin",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Melon,
        key: "melon",
        name: "Melon",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Cactus,
        key: "cactus",
        name: "Cactus",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::ShortGrass,
        key: "short_grass",
        name: "Short Grass",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Fern,
        key: "fern",
        name: "Fern",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Dandelion,
        key: "dandelion",
        name: "Dandelion",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Poppy,
        key: "poppy",
        name: "Poppy",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Cornflower,
        key: "cornflower",
        name: "Cornflower",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Allium,
        key: "allium",
        name: "Allium",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AzureBluet,
        key: "azure_bluet",
        name: "Azure Bluet",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::OxeyeDaisy,
        key: "oxeye_daisy",
        name: "Oxeye Daisy",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedTulip,
        key: "red_tulip",
        name: "Red Tulip",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DeadBush,
        key: "dead_bush",
        name: "Dead Bush",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BrownMushroom,
        key: "brown_mushroom",
        name: "Brown Mushroom",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedMushroom,
        key: "red_mushroom",
        name: "Red Mushroom",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Cobblestone,
        key: "cobblestone",
        name: "Cobblestone",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Smeltable],
    },
    ItemDef {
        item: ItemType::OakPlanks,
        key: "oak_planks",
        name: "Oak Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::SprucePlanks,
        key: "spruce_planks",
        name: "Spruce Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::BirchPlanks,
        key: "birch_planks",
        name: "Birch Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::JunglePlanks,
        key: "jungle_planks",
        name: "Jungle Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::AcaciaPlanks,
        key: "acacia_planks",
        name: "Acacia Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::DarkOakPlanks,
        key: "dark_oak_planks",
        name: "Dark Oak Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::CherryPlanks,
        key: "cherry_planks",
        name: "Cherry Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::MangrovePlanks,
        key: "mangrove_planks",
        name: "Mangrove Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::CraftingTable,
        key: "crafting_table",
        name: "Crafting Table",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Stick,
        key: "stick",
        name: "Stick",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WoodenPickaxe,
        key: "wooden_pickaxe",
        name: "Wooden Pickaxe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::StonePickaxe,
        key: "stone_pickaxe",
        name: "Stone Pickaxe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RawIron,
        key: "raw_iron",
        name: "Raw Iron",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Smeltable],
    },
    ItemDef {
        item: ItemType::RawCopper,
        key: "raw_copper",
        name: "Raw Copper",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Smeltable],
    },
    ItemDef {
        item: ItemType::Coal,
        key: "coal",
        name: "Coal",
        max_stack_size: STACK,
        held_pose: HeldPose {
            pitch: 0.0,
            yaw: 1.8,
            roll: 1.4,
        },
        tags: &[ItemTag::Fuel],
    },
    ItemDef {
        item: ItemType::IronIngot,
        key: "iron_ingot",
        name: "Iron Ingot",
        max_stack_size: STACK,
        held_pose: INGOT_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CopperIngot,
        key: "copper_ingot",
        name: "Copper Ingot",
        max_stack_size: STACK,
        held_pose: INGOT_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Furnace,
        key: "furnace",
        name: "Furnace",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Chest,
        // Key `chest` is what the chest recipe's result resolves to.
        key: "chest",
        name: "Chest",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Torch,
        // Key `torch` is what the torch recipe's result resolves to.
        key: "torch",
        name: "Torch",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Diamond,
        key: "diamond",
        name: "Diamond",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::LapisLazuli,
        key: "lapis_lazuli",
        name: "Lapis Lazuli",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RawGold,
        key: "raw_gold",
        name: "Raw Gold",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        // Smeltable: shift-clicks into the furnace input and smelts to a gold ingot.
        tags: &[ItemTag::Smeltable],
    },
    ItemDef {
        item: ItemType::GoldIngot,
        key: "gold_ingot",
        name: "Gold Ingot",
        max_stack_size: STACK,
        held_pose: INGOT_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WoodenAxe,
        key: "wooden_axe",
        name: "Wooden Axe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::StoneAxe,
        key: "stone_axe",
        name: "Stone Axe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::IronAxe,
        key: "iron_axe",
        name: "Iron Axe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DiamondAxe,
        key: "diamond_axe",
        name: "Diamond Axe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::IronPickaxe,
        key: "iron_pickaxe",
        name: "Iron Pickaxe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DiamondPickaxe,
        key: "diamond_pickaxe",
        name: "Diamond Pickaxe",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WoodenShovel,
        key: "wooden_shovel",
        name: "Wooden Shovel",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::StoneShovel,
        key: "stone_shovel",
        name: "Stone Shovel",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::IronShovel,
        key: "iron_shovel",
        name: "Iron Shovel",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DiamondShovel,
        key: "diamond_shovel",
        name: "Diamond Shovel",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::FurnitureWorkbench,
        key: "furniture_workbench",
        name: "Furniture Workbench",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    // Saplings: ordinary stackable block-items, held upright like a flower (the
    // shared `HeldPose::DEFAULT`). Placed on grass/dirt; grow into trees.
    ItemDef {
        item: ItemType::OakSapling,
        key: "oak_sapling",
        name: "Oak Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::SpruceSapling,
        key: "spruce_sapling",
        name: "Spruce Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BirchSapling,
        key: "birch_sapling",
        name: "Birch Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::JungleSapling,
        key: "jungle_sapling",
        name: "Jungle Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AcaciaSapling,
        key: "acacia_sapling",
        name: "Acacia Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DarkOakSapling,
        key: "dark_oak_sapling",
        name: "Dark Oak Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CherrySapling,
        key: "cherry_sapling",
        name: "Cherry Sapling",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::OakDoor,
        key: "oak_door",
        name: "Oak Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::SpruceDoor,
        key: "spruce_door",
        name: "Spruce Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BirchDoor,
        key: "birch_door",
        name: "Birch Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::JungleDoor,
        key: "jungle_door",
        name: "Jungle Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AcaciaDoor,
        key: "acacia_door",
        name: "Acacia Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DarkOakDoor,
        key: "dark_oak_door",
        name: "Dark Oak Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CherryDoor,
        key: "cherry_door",
        name: "Cherry Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::MangroveDoor,
        key: "mangrove_door",
        name: "Mangrove Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedwoodLog,
        key: "redwood_log",
        name: "Redwood Log",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Logs],
    },
    ItemDef {
        item: ItemType::RedwoodLeaves,
        key: "redwood_leaves",
        name: "Redwood Leaves",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedwoodPlanks,
        key: "redwood_planks",
        name: "Redwood Planks",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[ItemTag::Planks],
    },
    ItemDef {
        item: ItemType::RedwoodDoor,
        key: "redwood_door",
        name: "Redwood Door",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::OakStairs,
        key: "oak_stairs",
        name: "Oak Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::SpruceStairs,
        key: "spruce_stairs",
        name: "Spruce Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BirchStairs,
        key: "birch_stairs",
        name: "Birch Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::JungleStairs,
        key: "jungle_stairs",
        name: "Jungle Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::AcaciaStairs,
        key: "acacia_stairs",
        name: "Acacia Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DarkOakStairs,
        key: "dark_oak_stairs",
        name: "Dark Oak Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CherryStairs,
        key: "cherry_stairs",
        name: "Cherry Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::MangroveStairs,
        key: "mangrove_stairs",
        name: "Mangrove Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::RedwoodStairs,
        key: "redwood_stairs",
        name: "Redwood Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::CobblestoneStairs,
        key: "cobblestone_stairs",
        name: "Cobblestone Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::StoneStairs,
        key: "stone_stairs",
        name: "Stone Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::DirtStairs,
        key: "dirt_stairs",
        name: "Dirt Stairs",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WoodenBucket,
        key: "wooden_bucket",
        name: "Wooden Bucket",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::WaterBucket,
        key: "water_bucket",
        name: "Water Bucket",
        // A bucket of water is one unit of water: it never stacks, so filling /
        // pouring is always a one-for-one held-item swap.
        max_stack_size: 1,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Shears,
        key: "shears",
        name: "Shears",
        max_stack_size: STACK,
        held_pose: TOOL_POSE,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Wool,
        key: "wool",
        name: "Wool",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::BedFrame,
        key: "bed_frame",
        name: "Bed Frame",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
    ItemDef {
        item: ItemType::Bed,
        key: "bed",
        name: "Bed",
        max_stack_size: STACK,
        held_pose: HeldPose::DEFAULT,
        tags: &[],
    },
];

#[inline]
pub(super) fn from_id(id: u8) -> ItemType {
    ITEM_DEFS.get(id as usize).map_or(ItemType::Air, |d| d.item)
}

#[inline]
pub(super) fn def(item: ItemType) -> &'static ItemDef {
    &ITEM_DEFS[item.id() as usize]
}
