//! Worldgen's memo facility: every cache of positional generation facts in one
//! budgeted, observable, clearable object.
//!
//! A [`GenCaches`] belongs to a world. It is sized from that world's view
//! distance and worker count ([`CacheBudget`]), reports each memo's capacity,
//! occupancy, heap and hit rate ([`GenCaches::report`], fed to the memory
//! census), and is emptied when the world closes ([`GenCaches::clear`]). The
//! world [`install`]s it; every generator built afterwards captures it
//! ([`installed`]) and hands it down to the stages, the way the mod hook
//! config travels. Every shared key starts with a [`GenContext`] — the seed
//! and the content fingerprints of the catalogs a value derives from — so a
//! memo never answers across worlds or packs, and never by table address.
//!
//! Three tiers:
//! - shared memos (`memo::Memo`) inside [`GenCaches`] — the positional
//!   facts whose working set grows with the explored frontier;
//! - per-thread front tables (`local`) — small, fixed, direct-mapped copies
//!   of the hottest shared facts, billed per live thread and emptied with the
//!   world's caches;
//! - process tables (`ProcessCaches`) — seed-derived noise generators,
//!   bounded by the number of formulas, not by where anyone has walked.

mod context;
pub(crate) mod local;
pub(crate) mod memo;

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, LazyLock, PoisonError, RwLock};

use petramond_world::section::BlockCube;

pub use context::GenContext;
pub(crate) use memo::{Memo, MemoSpec};

/// How a memo's capacity follows the [`CacheBudget`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scaling {
    /// Keyed by position: the working set is the generation frontier, which
    /// grows with view distance and with the columns in flight at once.
    Frontier,
    /// Keyed by something a world has a bounded number of (query batches,
    /// noise instances): the reference capacity always.
    Fixed,
}

/// How large a world's memos are, relative to the capacities they were tuned
/// at: a [`RENDER_DIST`](petramond_world::world::load_targets::RENDER_DIST)
/// view generated by [`REFERENCE_WORKERS`](Self::REFERENCE_WORKERS) threads.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CacheBudget {
    scale: f64,
}

impl CacheBudget {
    /// The tuning point: every memo at its declared capacity. Tools and tests
    /// that never size a world use it.
    pub const REFERENCE: Self = Self { scale: 1.0 };
    /// Generation threads the declared capacities were tuned with.
    pub const REFERENCE_WORKERS: usize = 8;
    /// The smallest and largest multiple of the declared capacities.
    const SCALE_RANGE: (f64, f64) = (0.5, 4.0);

    /// Memos for a world streaming `view_distance` chunks around each viewer
    /// with `workers` generation threads. The frontier a streamer generates
    /// grows with the view radius, and each thread in flight works its own
    /// neighbourhood; whichever demands more sets the scale.
    pub fn for_world(view_distance: i32, workers: usize) -> Self {
        let reference_view = f64::from(petramond_world::world::load_targets::RENDER_DIST);
        let view = f64::from(view_distance.max(1)) / reference_view;
        let threads = workers.max(1) as f64 / Self::REFERENCE_WORKERS as f64;
        Self {
            scale: view
                .max(threads)
                .clamp(Self::SCALE_RANGE.0, Self::SCALE_RANGE.1),
        }
    }

    /// Entries for a memo declared at `base` under `scaling`: a power of two.
    pub(crate) fn capacity(self, base: usize, scaling: Scaling) -> usize {
        match scaling {
            Scaling::Fixed => base.next_power_of_two(),
            Scaling::Frontier => ((base as f64 * self.scale).round() as usize).next_power_of_two(),
        }
    }
}

/// One memo's line in the cache report.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct MemoStats {
    pub name: &'static str,
    /// Shared by every worker (`true`), or one copy per thread.
    pub shared: bool,
    /// Entries the memo may hold (across every live thread for a local one).
    pub capacity: usize,
    /// Entries held now (not tracked for per-thread tables).
    pub entries: usize,
    /// Resident bytes: the table, plus the heap its values hold.
    pub bytes: u64,
    pub hits: u64,
    pub misses: u64,
}

impl MemoStats {
    /// Hits over lookups, `None` before the first lookup.
    pub fn hit_rate(&self) -> Option<f64> {
        let lookups = self.hits + self.misses;
        (lookups > 0).then(|| self.hits as f64 / lookups as f64)
    }
}

/// Declares a group of named memos with its constructor, report and clear.
macro_rules! memo_group {
    (
        $(#[$meta:meta])*
        $vis:vis struct $group:ident {
            $(
                $(#[$doc:meta])*
                $field:ident: $key:ty => $value:ty =
                    ($name:literal, $capacity:expr, $scaling:ident, $weigh:expr),
            )*
        }
    ) => {
        $(#[$meta])*
        $vis struct $group {
            $( $(#[$doc])* pub(super) $field: $crate::cache::Memo<$key, $value>, )*
        }

        impl $group {
            pub(crate) fn new(budget: $crate::cache::CacheBudget) -> Self {
                Self {
                    $(
                        $field: $crate::cache::Memo::new(
                            $crate::cache::MemoSpec {
                                name: $name,
                                capacity: $capacity,
                                scaling: $crate::cache::Scaling::$scaling,
                                weigh: $weigh,
                            },
                            budget,
                        ),
                    )*
                }
            }

            pub(crate) fn stats(&self) -> Vec<$crate::cache::MemoStats> {
                vec![$( self.$field.stats(), )*]
            }

            pub(crate) fn clear(&self) {
                $( self.$field.clear(); )*
            }
        }
    };
}
pub(crate) use memo_group;

/// Inline bytes only: the value holds no heap of its own.
pub(crate) fn inline<V>(_: &V) -> usize {
    0
}

/// The pointee of a shared value, billed once per entry.
pub(crate) fn pointee<T>(_: &Arc<T>) -> usize {
    std::mem::size_of::<T>()
}

/// A shared slice's elements.
pub(crate) fn slice<T>(v: &Arc<[T]>) -> usize {
    std::mem::size_of_val(&**v)
}

/// A block cube's id storage.
fn cube_heap(cube: &BlockCube) -> usize {
    cube.heap().1 as usize
}

memo_group! {
    /// The terrain-side memos: section terrain before features, the feature
    /// window tiles, and the positional host queries' answers.
    pub(crate) struct TerrainCaches {
        /// A section's filled and carved blocks (see `section_memo`).
        section_cubes: crate::section_memo::Key => BlockCube =
            ("terrain.section_cubes", 8192, Frontier, cube_heap),
        /// A section's solid/fluid/air mask — kept longer than the cubes it
        /// is derived from because it is sixteen times smaller.
        section_spaces: crate::section_memo::Key => Arc<crate::section_memo::SpaceMask> =
            ("terrain.section_spaces", 16_384, Frontier, pointee),
        /// A 16×16 world tile of raw surfaces, cave-adjusted surfaces and
        /// biomes: the feature windows, the column core and the terrain
        /// queries all read these.
        surface_tiles: crate::feature::TileKey => Arc<crate::feature::RegionTile> =
            ("terrain.surface_tiles", 2048, Frontier, pointee),
        /// The underground biome ids that can occur in a queried box.
        underground_boxes: crate::UndergroundBoxKey => Arc<[u8]> =
            ("terrain.underground_boxes", 4096, Frontier, slice),
    }
}

/// One world's worldgen memos. See the module docs.
pub struct GenCaches {
    budget: CacheBudget,
    pub(crate) terrain: TerrainCaches,
    pub(crate) caves: crate::noise::cave_field::CaveCaches,
}

impl GenCaches {
    pub fn new(budget: CacheBudget) -> Self {
        Self {
            budget,
            terrain: TerrainCaches::new(budget),
            caves: crate::noise::cave_field::CaveCaches::new(budget),
        }
    }

    pub fn budget(&self) -> CacheBudget {
        self.budget
    }

    /// Every memo this world's generation reads through: its own shared
    /// memos, then the per-thread and process tables it shares with every
    /// other world in the process.
    pub fn report(&self) -> Vec<MemoStats> {
        let mut out = self.terrain.stats();
        out.extend(self.caves.stats());
        out.extend(local::stats());
        out.extend(process().stats());
        out
    }

    /// Resident bytes of [`report`](Self::report)'s memos.
    pub fn resident_bytes(&self) -> u64 {
        self.report().iter().map(|m| m.bytes).sum()
    }

    /// Drop every memoized value — what a world does when it closes. The
    /// tables stay allocated until the last generator holding them is gone;
    /// per-thread copies empty on their next lookup.
    pub fn clear(&self) {
        self.terrain.clear();
        self.caves.clear();
        local::clear_all();
    }
}

memo_group! {
    /// Seed-derived noise generators, interned process-wide: a formula's
    /// Perlin stacks for one seed are built once, however many worlds and
    /// queries use them. Bounded by the formulas a pack declares.
    pub(crate) struct ProcessCaches {
        noises: crate::formula::NoiseKey => Arc<crate::density::noise::ReferenceDoublePerlin> =
            ("process.noises", 256, Fixed, pointee),
    }
}

/// The process tables.
pub(crate) fn process() -> &'static ProcessCaches {
    static PROCESS: LazyLock<ProcessCaches> =
        LazyLock::new(|| ProcessCaches::new(CacheBudget::REFERENCE));
    &PROCESS
}

static INSTALLED: RwLock<Option<Arc<GenCaches>>> = RwLock::new(None);
static INSTALLED_EPOCH: AtomicU64 = AtomicU64::new(0);

/// Make `caches` the memos generators built from now on capture. Called by a
/// world that generates, before it submits its first job.
pub fn install(caches: Arc<GenCaches>) {
    *INSTALLED.write().unwrap_or_else(PoisonError::into_inner) = Some(caches);
    INSTALLED_EPOCH.fetch_add(1, Ordering::AcqRel);
}

/// The installed memos, or a reference-sized set for a process that never
/// installed any (tooling, tests), created on first use and kept installed.
pub fn installed() -> Arc<GenCaches> {
    if let Some(caches) = INSTALLED
        .read()
        .unwrap_or_else(PoisonError::into_inner)
        .as_ref()
    {
        return Arc::clone(caches);
    }
    let mut slot = INSTALLED.write().unwrap_or_else(PoisonError::into_inner);
    Arc::clone(slot.get_or_insert_with(|| Arc::new(GenCaches::new(CacheBudget::REFERENCE))))
}

/// Identity of the installed memos for cached-generator keys: a generator
/// built under an older epoch still holds the previous world's caches.
pub fn installed_epoch() -> u64 {
    INSTALLED_EPOCH.load(Ordering::Acquire)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_budget_scales_frontier_memos_within_bounds() {
        let reference_view = petramond_world::world::load_targets::RENDER_DIST;
        assert_eq!(
            CacheBudget::for_world(reference_view, CacheBudget::REFERENCE_WORKERS),
            CacheBudget::REFERENCE
        );
        let far = CacheBudget::for_world(reference_view * 2, 4);
        assert_eq!(far.capacity(8192, Scaling::Frontier), 16_384);
        assert_eq!(far.capacity(512, Scaling::Fixed), 512);
        let many = CacheBudget::for_world(8, CacheBudget::REFERENCE_WORKERS * 3);
        assert_eq!(many.capacity(1000, Scaling::Frontier), 4096);
        let tiny = CacheBudget::for_world(2, 1);
        assert_eq!(tiny.capacity(8192, Scaling::Frontier), 4096, "never below half");
        let huge = CacheBudget::for_world(reference_view * 100, 1);
        assert_eq!(huge.capacity(8192, Scaling::Frontier), 32_768, "never above four times");
    }

    /// A world's report names every memo exactly once, and generating fills
    /// it; clearing empties the shared memos.
    #[test]
    fn a_world_report_lists_every_memo_and_clears() {
        let caches = Arc::new(GenCaches::new(CacheBudget::REFERENCE));
        let report = caches.report();
        let mut names: Vec<_> = report.iter().map(|m| m.name).collect();
        names.sort_unstable();
        let unique = names.len();
        names.dedup();
        assert_eq!(unique, names.len(), "duplicate memo names in {names:?}");
        assert!(report.iter().all(|m| m.capacity.is_power_of_two() || !m.shared));

        let generator =
            crate::driver::ChunkGenerator::with_caches(0xCAC4_E001, None, Arc::clone(&caches));
        let col = generator.generate_column_gen(0, 0);
        let (lo, hi) = col.surf_range();
        for cy in [lo.div_euclid(16), hi.div_euclid(16)] {
            generator.generate_section(petramond_world::chunk::SectionPos::new(0, cy, 0), &col);
        }
        let shared = |caches: &GenCaches| -> usize {
            caches.report().iter().filter(|m| m.shared).map(|m| m.entries).sum()
        };
        assert!(shared(&caches) > 0, "generation filled no memo");
        let tiles = caches.terrain.surface_tiles.stats();
        assert!(tiles.entries > 0 && tiles.misses > 0);
        assert!(caches.resident_bytes() > 0);
        caches.clear();
        let after: usize = caches
            .terrain
            .stats()
            .into_iter()
            .chain(caches.caves.stats())
            .map(|m| m.entries)
            .sum();
        assert_eq!(after, 0, "a cleared world keeps memoized values");
    }
}
