use crate::atlas::Tile;
use crate::item::{Drop, DropSpec, ItemType};
use crate::registry::{self, RegistryKey, TableEntry};

use super::definition::{drops_self, BlockDef, BlockFlags, BlockMaterial};
use super::{behavior, Block, BlockTag};

const AIR_FLAGS: BlockFlags = BlockFlags::REPLACEABLE;
const FULL_CUBE_FLAGS: BlockFlags = BlockFlags::SOLID
    .with(BlockFlags::OPAQUE)
    .with(BlockFlags::AO_OCCLUDER);
const WATER_FLAGS: BlockFlags = BlockFlags::TRANSPARENT.with(BlockFlags::REPLACEABLE);
const LEAVES_FLAGS: BlockFlags = BlockFlags::SOLID
    .with(BlockFlags::AO_OCCLUDER)
    .with(BlockFlags::TRANSPARENT);
// Cross-model plants (grass, ferns, flowers, mushrooms): transparent cutout only.
// NOT solid (walk-through, not a build target), NOT opaque (neighbour cube faces
// still draw toward them and they don't cull), NOT an AO occluder, NOT replaceable.
const PLANT_FLAGS: BlockFlags = BlockFlags::TRANSPARENT;
// Chest: SOLID (collision, raycast, a build target) but NOT opaque and NOT an AO
// occluder — it's drawn as a custom inset model (the mesher skips its cell), so
// neighbours must keep their faces toward it and it casts no full-cube shadow.
const CHEST_FLAGS: BlockFlags = BlockFlags::SOLID;
// Torch: SOLID so the ray can select it (its real shape is far too thin to DDA),
// and TRANSPARENT so skylight/block-light flood through its cell and neighbours
// keep their faces toward it. NOT opaque, NOT an AO occluder, NOT replaceable —
// and its collision box is overridden to empty (see `Block::collision_boxes`), so
// the player walks through it. Drawn as a custom 3D pole (see `mesh::torch`).
const TORCH_FLAGS: BlockFlags = BlockFlags::SOLID.with(BlockFlags::TRANSPARENT);

pub(super) const ALL_BLOCKS: &[Block] = &[
    Block::Air,
    Block::Grass,
    Block::Dirt,
    Block::Stone,
    Block::Sand,
    Block::Snow,
    Block::Water,
    Block::OakLog,
    Block::OakLeaves,
    Block::SpruceLog,
    Block::BirchLog,
    Block::JungleLog,
    Block::AcaciaLog,
    Block::DarkOakLog,
    Block::CherryLog,
    Block::MangroveLog,
    Block::SpruceLeaves,
    Block::BirchLeaves,
    Block::JungleLeaves,
    Block::AcaciaLeaves,
    Block::DarkOakLeaves,
    Block::MangroveLeaves,
    Block::CherryLeaves,
    Block::AzaleaLeaves,
    Block::RedSand,
    Block::Sandstone,
    Block::RedSandstone,
    Block::Terracotta,
    Block::WhiteTerracotta,
    Block::OrangeTerracotta,
    Block::YellowTerracotta,
    Block::BrownTerracotta,
    Block::RedTerracotta,
    Block::LightGrayTerracotta,
    Block::Podzol,
    Block::Mycelium,
    Block::CoarseDirt,
    Block::Gravel,
    Block::Clay,
    Block::Mud,
    Block::MossBlock,
    Block::SnowBlock,
    Block::PackedIce,
    Block::Ice,
    Block::Calcite,
    Block::Granite,
    Block::Diorite,
    Block::Andesite,
    Block::Tuff,
    Block::CoalOre,
    Block::IronOre,
    Block::CopperOre,
    Block::GoldOre,
    Block::RedstoneOre,
    Block::LapisOre,
    Block::DiamondOre,
    Block::EmeraldOre,
    Block::Pumpkin,
    Block::Melon,
    Block::Cactus,
    Block::ShortGrass,
    Block::Fern,
    Block::Dandelion,
    Block::Poppy,
    Block::Cornflower,
    Block::Allium,
    Block::AzureBluet,
    Block::OxeyeDaisy,
    Block::RedTulip,
    Block::DeadBush,
    Block::BrownMushroom,
    Block::RedMushroom,
    Block::Cobblestone,
    Block::OakPlanks,
    Block::SprucePlanks,
    Block::BirchPlanks,
    Block::JunglePlanks,
    Block::AcaciaPlanks,
    Block::DarkOakPlanks,
    Block::CherryPlanks,
    Block::MangrovePlanks,
    Block::CraftingTable,
    Block::Furnace,
    Block::Chest,
    Block::Torch,
];

pub(super) const BLOCK_DEFS: &[BlockDef] = &[
    BlockDef {
        block: Block::Air,
        tags: &[],
        behavior: &behavior::INERT,
        flags: AIR_FLAGS,
        tiles: [Tile::OakLeaves, Tile::OakLeaves, Tile::OakLeaves],
        material: BlockMaterial::None,
        harvest_tier: 0,
        hardness: -1.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::Grass,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::GrassTop, Tile::Dirt, Tile::GrassSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Grass),
    },
    BlockDef {
        block: Block::Dirt,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Dirt, Tile::Dirt, Tile::Dirt],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Dirt),
    },
    BlockDef {
        block: Block::Stone,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Stone, Tile::Stone, Tile::Stone],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        // Mined stone yields cobblestone (needs a wooden pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Cobblestone,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::Sand,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Sand, Tile::Sand, Tile::Sand],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Sand),
    },
    BlockDef {
        block: Block::Snow,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Snow, Tile::Dirt, Tile::GrassSnow],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Snow),
    },
    BlockDef {
        block: Block::Water,
        tags: &[],
        behavior: &behavior::WATER,
        flags: WATER_FLAGS,
        tiles: [Tile::Water, Tile::Water, Tile::Water],
        material: BlockMaterial::None,
        harvest_tier: 0,
        hardness: -1.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::OakLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::OakLogTop, Tile::OakLogTop, Tile::OakLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(OakLog),
    },
    BlockDef {
        block: Block::OakLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::OakLeaves, Tile::OakLeaves, Tile::OakLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(OakLeaves),
    },
    BlockDef {
        block: Block::SpruceLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::SpruceLogTop, Tile::SpruceLogTop, Tile::SpruceLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(SpruceLog),
    },
    BlockDef {
        block: Block::BirchLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::BirchLogTop, Tile::BirchLogTop, Tile::BirchLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(BirchLog),
    },
    BlockDef {
        block: Block::JungleLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::JungleLogTop, Tile::JungleLogTop, Tile::JungleLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(JungleLog),
    },
    BlockDef {
        block: Block::AcaciaLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::AcaciaLogTop, Tile::AcaciaLogTop, Tile::AcaciaLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(AcaciaLog),
    },
    BlockDef {
        block: Block::DarkOakLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::DarkOakLogTop,
            Tile::DarkOakLogTop,
            Tile::DarkOakLogSide,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(DarkOakLog),
    },
    BlockDef {
        block: Block::CherryLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CherryLogTop, Tile::CherryLogTop, Tile::CherryLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(CherryLog),
    },
    BlockDef {
        block: Block::MangroveLog,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::MangroveLogTop,
            Tile::MangroveLogTop,
            Tile::MangroveLogSide,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(MangroveLog),
    },
    BlockDef {
        block: Block::SpruceLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::SpruceLeaves, Tile::SpruceLeaves, Tile::SpruceLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(SpruceLeaves),
    },
    BlockDef {
        block: Block::BirchLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::BirchLeaves, Tile::BirchLeaves, Tile::BirchLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(BirchLeaves),
    },
    BlockDef {
        block: Block::JungleLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::JungleLeaves, Tile::JungleLeaves, Tile::JungleLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(JungleLeaves),
    },
    BlockDef {
        block: Block::AcaciaLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::AcaciaLeaves, Tile::AcaciaLeaves, Tile::AcaciaLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(AcaciaLeaves),
    },
    BlockDef {
        block: Block::DarkOakLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [
            Tile::DarkOakLeaves,
            Tile::DarkOakLeaves,
            Tile::DarkOakLeaves,
        ],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(DarkOakLeaves),
    },
    BlockDef {
        block: Block::MangroveLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [
            Tile::MangroveLeaves,
            Tile::MangroveLeaves,
            Tile::MangroveLeaves,
        ],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(MangroveLeaves),
    },
    BlockDef {
        block: Block::CherryLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::CherryLeaves, Tile::CherryLeaves, Tile::CherryLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(CherryLeaves),
    },
    BlockDef {
        block: Block::AzaleaLeaves,
        tags: &[BlockTag::Leaves],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::AzaleaLeaves, Tile::AzaleaLeaves, Tile::AzaleaLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(AzaleaLeaves),
    },
    BlockDef {
        block: Block::RedSand,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::RedSand, Tile::RedSand, Tile::RedSand],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(RedSand),
    },
    BlockDef {
        block: Block::Sandstone,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::SandstoneTop,
            Tile::SandstoneBottom,
            Tile::SandstoneSide,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Sandstone),
    },
    BlockDef {
        block: Block::RedSandstone,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::RedSandstoneTop,
            Tile::RedSandstoneBottom,
            Tile::RedSandstoneSide,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(RedSandstone),
    },
    BlockDef {
        block: Block::Terracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Terracotta, Tile::Terracotta, Tile::Terracotta],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Terracotta),
    },
    BlockDef {
        block: Block::WhiteTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::WhiteTerracotta,
            Tile::WhiteTerracotta,
            Tile::WhiteTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(WhiteTerracotta),
    },
    BlockDef {
        block: Block::OrangeTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::OrangeTerracotta,
            Tile::OrangeTerracotta,
            Tile::OrangeTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(OrangeTerracotta),
    },
    BlockDef {
        block: Block::YellowTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::YellowTerracotta,
            Tile::YellowTerracotta,
            Tile::YellowTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(YellowTerracotta),
    },
    BlockDef {
        block: Block::BrownTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::BrownTerracotta,
            Tile::BrownTerracotta,
            Tile::BrownTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(BrownTerracotta),
    },
    BlockDef {
        block: Block::RedTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::RedTerracotta,
            Tile::RedTerracotta,
            Tile::RedTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(RedTerracotta),
    },
    BlockDef {
        block: Block::LightGrayTerracotta,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::LightGrayTerracotta,
            Tile::LightGrayTerracotta,
            Tile::LightGrayTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(LightGrayTerracotta),
    },
    BlockDef {
        block: Block::Podzol,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PodzolTop, Tile::Dirt, Tile::PodzolSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Podzol),
    },
    BlockDef {
        block: Block::Mycelium,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MyceliumTop, Tile::Dirt, Tile::MyceliumSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Mycelium),
    },
    BlockDef {
        block: Block::CoarseDirt,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CoarseDirt, Tile::CoarseDirt, Tile::CoarseDirt],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(CoarseDirt),
    },
    BlockDef {
        block: Block::Gravel,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Gravel, Tile::Gravel, Tile::Gravel],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Gravel),
    },
    BlockDef {
        block: Block::Clay,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Clay, Tile::Clay, Tile::Clay],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Clay),
    },
    BlockDef {
        block: Block::Mud,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Mud, Tile::Mud, Tile::Mud],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Mud),
    },
    BlockDef {
        block: Block::MossBlock,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MossBlock, Tile::MossBlock, Tile::MossBlock],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(MossBlock),
    },
    BlockDef {
        block: Block::SnowBlock,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Snow, Tile::Snow, Tile::Snow],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(SnowBlock),
    },
    BlockDef {
        block: Block::PackedIce,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PackedIce, Tile::PackedIce, Tile::PackedIce],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 0.5,
        drop: drops_self!(PackedIce),
    },
    BlockDef {
        block: Block::Ice,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Ice, Tile::Ice, Tile::Ice],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 0.5,
        drop: drops_self!(Ice),
    },
    BlockDef {
        block: Block::Calcite,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Calcite, Tile::Calcite, Tile::Calcite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Calcite),
    },
    BlockDef {
        block: Block::Granite,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Granite, Tile::Granite, Tile::Granite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Granite),
    },
    BlockDef {
        block: Block::Diorite,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Diorite, Tile::Diorite, Tile::Diorite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Diorite),
    },
    BlockDef {
        block: Block::Andesite,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Andesite, Tile::Andesite, Tile::Andesite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Andesite),
    },
    BlockDef {
        block: Block::Tuff,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Tuff, Tile::Tuff, Tile::Tuff],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Tuff),
    },
    BlockDef {
        block: Block::CoalOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CoalOre, Tile::CoalOre, Tile::CoalOre],
        material: BlockMaterial::Ore,
        harvest_tier: 1,
        hardness: 3.0,
        // Coal ore → one coal (wooden pickaxe or better).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Coal,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::IronOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::IronOre, Tile::IronOre, Tile::IronOre],
        material: BlockMaterial::Ore,
        harvest_tier: 2,
        hardness: 3.0,
        // Iron ore → one raw iron (needs a stone pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::RawIron,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::CopperOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CopperOre, Tile::CopperOre, Tile::CopperOre],
        material: BlockMaterial::Ore,
        harvest_tier: 2,
        hardness: 3.0,
        // Copper ore → 2–4 raw copper (needs a stone pickaxe).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::RawCopper,
                min: 2,
                max: 4,
            }],
        },
    },
    BlockDef {
        block: Block::GoldOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::GoldOre, Tile::GoldOre, Tile::GoldOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(GoldOre),
    },
    BlockDef {
        block: Block::RedstoneOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::RedstoneOre, Tile::RedstoneOre, Tile::RedstoneOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(RedstoneOre),
    },
    BlockDef {
        block: Block::LapisOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::LapisOre, Tile::LapisOre, Tile::LapisOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(LapisOre),
    },
    BlockDef {
        block: Block::DiamondOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::DiamondOre, Tile::DiamondOre, Tile::DiamondOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(DiamondOre),
    },
    BlockDef {
        block: Block::EmeraldOre,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::EmeraldOre, Tile::EmeraldOre, Tile::EmeraldOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(EmeraldOre),
    },
    BlockDef {
        block: Block::Pumpkin,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PumpkinTop, Tile::PumpkinTop, Tile::PumpkinSide],
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 1.0,
        drop: drops_self!(Pumpkin),
    },
    BlockDef {
        block: Block::Melon,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MelonTop, Tile::MelonTop, Tile::MelonSide],
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 1.0,
        drop: drops_self!(Melon),
    },
    BlockDef {
        block: Block::Cactus,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CactusTop, Tile::CactusBottom, Tile::CactusSide],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.4,
        drop: drops_self!(Cactus),
    },
    BlockDef {
        block: Block::ShortGrass,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::ShortGrass, Tile::ShortGrass, Tile::ShortGrass],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::Fern,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::Fern, Tile::Fern, Tile::Fern],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Fern),
    },
    BlockDef {
        block: Block::Dandelion,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::Dandelion, Tile::Dandelion, Tile::Dandelion],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Dandelion),
    },
    BlockDef {
        block: Block::Poppy,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::Poppy, Tile::Poppy, Tile::Poppy],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Poppy),
    },
    BlockDef {
        block: Block::Cornflower,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::Cornflower, Tile::Cornflower, Tile::Cornflower],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Cornflower),
    },
    BlockDef {
        block: Block::Allium,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::Allium, Tile::Allium, Tile::Allium],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Allium),
    },
    BlockDef {
        block: Block::AzureBluet,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::AzureBluet, Tile::AzureBluet, Tile::AzureBluet],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(AzureBluet),
    },
    BlockDef {
        block: Block::OxeyeDaisy,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::OxeyeDaisy, Tile::OxeyeDaisy, Tile::OxeyeDaisy],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(OxeyeDaisy),
    },
    BlockDef {
        block: Block::RedTulip,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::RedTulip, Tile::RedTulip, Tile::RedTulip],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(RedTulip),
    },
    BlockDef {
        block: Block::DeadBush,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::DeadBush, Tile::DeadBush, Tile::DeadBush],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(DeadBush),
    },
    BlockDef {
        block: Block::BrownMushroom,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [
            Tile::BrownMushroom,
            Tile::BrownMushroom,
            Tile::BrownMushroom,
        ],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(BrownMushroom),
    },
    BlockDef {
        block: Block::RedMushroom,
        tags: &[],
        behavior: &behavior::INERT,
        flags: PLANT_FLAGS,
        tiles: [Tile::RedMushroom, Tile::RedMushroom, Tile::RedMushroom],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(RedMushroom),
    },
    // --- Crafting update: crafted/placeable blocks. ---
    BlockDef {
        block: Block::Cobblestone,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Cobblestone, Tile::Cobblestone, Tile::Cobblestone],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 2.0,
        drop: drops_self!(Cobblestone),
    },
    BlockDef {
        block: Block::OakPlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::OakPlanks, Tile::OakPlanks, Tile::OakPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(OakPlanks),
    },
    BlockDef {
        block: Block::SprucePlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::SprucePlanks, Tile::SprucePlanks, Tile::SprucePlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(SprucePlanks),
    },
    BlockDef {
        block: Block::BirchPlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::BirchPlanks, Tile::BirchPlanks, Tile::BirchPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(BirchPlanks),
    },
    BlockDef {
        block: Block::JunglePlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::JunglePlanks, Tile::JunglePlanks, Tile::JunglePlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(JunglePlanks),
    },
    BlockDef {
        block: Block::AcaciaPlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::AcaciaPlanks, Tile::AcaciaPlanks, Tile::AcaciaPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(AcaciaPlanks),
    },
    BlockDef {
        block: Block::DarkOakPlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::DarkOakPlanks,
            Tile::DarkOakPlanks,
            Tile::DarkOakPlanks,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(DarkOakPlanks),
    },
    BlockDef {
        block: Block::CherryPlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CherryPlanks, Tile::CherryPlanks, Tile::CherryPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(CherryPlanks),
    },
    BlockDef {
        block: Block::MangrovePlanks,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::MangrovePlanks,
            Tile::MangrovePlanks,
            Tile::MangrovePlanks,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(MangrovePlanks),
    },
    BlockDef {
        block: Block::CraftingTable,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        // [top, bottom, side]: the 3-tile model uses one side texture for all
        // four faces, so the recognizable front art is shown on every side.
        tiles: [
            Tile::CraftingTableTop,
            Tile::OakPlanks,
            Tile::CraftingTableFront,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.5,
        drop: drops_self!(CraftingTable),
    },
    BlockDef {
        block: Block::Furnace,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        // [top, bottom, side]: the placed furnace is meshed directionally (front on
        // the facing face, `furnace_side` on the others — see mesh::builder), so the
        // default side is `furnace_side`. The inventory/held item cube puts the
        // front on one visible face via `render::block_model::block_icon_faces`.
        tiles: [Tile::FurnaceTop, Tile::FurnaceTop, Tile::FurnaceSide],
        // Stone material → needs at least a wooden pickaxe to harvest.
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 3.5,
        drop: drops_self!(Furnace),
    },
    BlockDef {
        block: Block::Chest,
        tags: &[],
        behavior: &behavior::INERT,
        // SOLID but non-opaque: the placed chest is drawn as a custom inset body +
        // hinged lid (the mesher skips its cell — see render::chest_model), so
        // neighbours keep their faces toward it and it casts no full-cube shadow.
        flags: CHEST_FLAGS,
        // [top, bottom, side] feeds only the inventory/held icon now (the placed block
        // is drawn from its own model). The icon overrides the front face via
        // render::block_model::block_icon_faces. Bottom reuses the side tile (the
        // vanilla chest bottom is unpainted and never visible).
        tiles: [Tile::ChestTop, Tile::ChestSide, Tile::ChestSide],
        // Wood → hand-harvestable (no pickaxe needed), like planks/crafting table.
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.5,
        drop: drops_self!(Chest),
    },
    BlockDef {
        block: Block::Torch,
        tags: &[],
        behavior: &behavior::INERT,
        flags: TORCH_FLAGS,
        // [top, bottom, side]: the in-world pole (see mesh::torch) caps the top with
        // the flame tile and wraps the four thin sides with the center-strip body;
        // the bottom reuses the strip (it sits against the support and is unseen).
        // The inventory icon / held item use the full `Tile::Torch` sprite instead
        // (see ItemType::render_kind), so these per-face tiles only feed the model.
        tiles: [Tile::TorchTop, Tile::TorchSide, Tile::TorchSide],
        // Manufactured object, not a plant: instant to break, hand-harvestable,
        // drops itself. `Other` keeps it out of the tool-gated Stone/Ore set.
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Torch),
    },
];

impl RegistryKey for Block {
    #[inline]
    fn to_id(self) -> u8 {
        self.id()
    }
}

impl TableEntry for BlockDef {
    type Key = Block;
    #[inline]
    fn key(&self) -> Block {
        self.block
    }
}

#[inline]
pub(super) fn from_id(id: u8) -> Block {
    registry::from_id(BLOCK_DEFS, id, Block::Air)
}

#[inline]
pub(super) fn def(block: Block) -> &'static BlockDef {
    registry::def(BLOCK_DEFS, block)
}
