use crate::atlas::Tile;
use crate::block_model::BlockModelKind;
use crate::item::{Drop, DropSpec, ItemType};
use crate::registry::{self, RegistryKey, TableEntry};

use super::definition::{drops_self, BlockDef, BlockFlags, BlockMaterial};
use super::{behavior, Aabb, Block, BlockTag, RenderShape};

const AIR_FLAGS: BlockFlags = BlockFlags::NONE;
const FULL_CUBE_FLAGS: BlockFlags = BlockFlags::SOLID
    .with(BlockFlags::OPAQUE)
    .with(BlockFlags::AO_OCCLUDER);
const WATER_FLAGS: BlockFlags = BlockFlags::TRANSPARENT;
const LEAVES_FLAGS: BlockFlags = BlockFlags::SOLID
    .with(BlockFlags::AO_OCCLUDER)
    .with(BlockFlags::TRANSPARENT);
// Cross-model plants (grass, ferns, flowers, mushrooms): transparent cutout only.
// NOT solid (walk-through, not a build target), NOT opaque (neighbour cube faces
// still draw toward them and they don't cull), NOT an AO occluder. Replaceability
// and fragility are now BlockTags on the per-plant rows, not flags.
const PLANT_FLAGS: BlockFlags = BlockFlags::TRANSPARENT;
// Chest: SOLID (collision, raycast, a build target) but NOT opaque and NOT an AO
// occluder — it's drawn as a custom inset model (the mesher skips its cell), so
// neighbours must keep their faces toward it and it casts no full-cube shadow.
const CHEST_FLAGS: BlockFlags = BlockFlags::SOLID;
// Torch: NOT solid — a thin decoration, not a block that obstructs, supports, or
// smothers, so it must never count as a solid block (e.g. as cover over grass).
// TRANSPARENT so skylight/block-light flood through its cell and neighbours keep
// their faces toward it. NOT opaque, NOT an AO occluder, NOT replaceable, and no
// collision (see `Block::collision_boxes`), so the player walks through it. The
// raycast still selects it — by its `RenderShape::Torch` (its real pole is too thin
// to DDA on cell entry), NOT by solidity. Drawn as a custom 3D pole (`mesh::torch`).
const TORCH_FLAGS: BlockFlags = BlockFlags::TRANSPARENT;
// bbmodel block (e.g. the workbench): SOLID (collision, raycast, a build target) but
// NOT opaque and NOT an AO occluder — like the chest it is drawn from its own model and
// the mesher skips its cell, so neighbours keep their faces toward it and it casts no
// full-cube shadow. Its real collision/selection come from the model (per cell), not the
// data row (see `Block::collision_boxes` / `block_model`).
const MODEL_FLAGS: BlockFlags = BlockFlags::SOLID;
// Cactus: a SOLID cube that is NOT opaque. Its four sides are inset 1px (see
// `mesh::face::cactus_quad`) so they don't cover the cell's faces — marking it a full
// opaque cube would cull the NEIGHBOURS' faces toward it and leave a see-through gap
// behind the recessed trunk. Non-opaque keeps those neighbour faces drawn (the fix); it
// still occludes AO, so it grounds with a contact shadow like leaves. The only trade-off
// (no full-cube skylight shadow) is fine for an open-desert plant. Its sand-only
// placement and break-when-undermined come from the row's tags/behaviour, not these flags.
const CACTUS_FLAGS: BlockFlags = BlockFlags::SOLID.with(BlockFlags::AO_OCCLUDER);

// Collision shapes the rows below point at. `NO_BOXES` = no collision (air, water,
// walk-through plants, and the torch — selectable by its shape but stepped through);
// `FULL_CUBE_BOXES` = the whole cell; `CHEST_BOXES` = the inset chest body+lid
// (matches `render::chest_model`, so collision/outline/crack hug the chest).
const NO_BOXES: &[Aabb] = &[];
const FULL_CUBE_BOXES: &[Aabb] = &[Aabb {
    min: [0.0, 0.0, 0.0],
    max: [1.0, 1.0, 1.0],
}];
const CHEST_BOXES: &[Aabb] = &[Aabb {
    min: [1.0 / 16.0, 0.0, 1.0 / 16.0],
    max: [15.0 / 16.0, 14.0 / 16.0, 15.0 / 16.0],
}];
// Cactus: the body is inset 1px on its four sides (the mesh recesses the side faces
// so the spines stand proud — see `mesh::face::cactus_quad`), full height. Collision
// AND the selection outline / break overlay (their union, via `Block::visual_aabb`)
// hug this inset body, so you collide with and target the 14-wide trunk, not the cell.
const CACTUS_BOXES: &[Aabb] = &[Aabb {
    min: [1.0 / 16.0, 0.0, 1.0 / 16.0],
    max: [15.0 / 16.0, 1.0, 15.0 / 16.0],
}];

pub(super) const ALL_BLOCKS: &[Block] = &[
    Block::Air,
    Block::Grass,
    Block::Dirt,
    Block::Stone,
    Block::Sand,
    Block::Snow,
    Block::Water,
    Block::OakLog,
    Block::OakLeaves,
    Block::SpruceLog,
    Block::BirchLog,
    Block::JungleLog,
    Block::AcaciaLog,
    Block::DarkOakLog,
    Block::CherryLog,
    Block::MangroveLog,
    Block::SpruceLeaves,
    Block::BirchLeaves,
    Block::JungleLeaves,
    Block::AcaciaLeaves,
    Block::DarkOakLeaves,
    Block::MangroveLeaves,
    Block::CherryLeaves,
    Block::AzaleaLeaves,
    Block::RedSand,
    Block::Sandstone,
    Block::RedSandstone,
    Block::Terracotta,
    Block::WhiteTerracotta,
    Block::OrangeTerracotta,
    Block::YellowTerracotta,
    Block::BrownTerracotta,
    Block::RedTerracotta,
    Block::LightGrayTerracotta,
    Block::Podzol,
    Block::Mycelium,
    Block::CoarseDirt,
    Block::Gravel,
    Block::Clay,
    Block::Mud,
    Block::MossBlock,
    Block::SnowBlock,
    Block::PackedIce,
    Block::Ice,
    Block::Calcite,
    Block::Granite,
    Block::Diorite,
    Block::Andesite,
    Block::Tuff,
    Block::CoalOre,
    Block::IronOre,
    Block::CopperOre,
    Block::GoldOre,
    Block::RedstoneOre,
    Block::LapisOre,
    Block::DiamondOre,
    Block::EmeraldOre,
    Block::Pumpkin,
    Block::Melon,
    Block::Cactus,
    Block::ShortGrass,
    Block::Fern,
    Block::Dandelion,
    Block::Poppy,
    Block::Cornflower,
    Block::Allium,
    Block::AzureBluet,
    Block::OxeyeDaisy,
    Block::RedTulip,
    Block::DeadBush,
    Block::BrownMushroom,
    Block::RedMushroom,
    Block::Cobblestone,
    Block::OakPlanks,
    Block::SprucePlanks,
    Block::BirchPlanks,
    Block::JunglePlanks,
    Block::AcaciaPlanks,
    Block::DarkOakPlanks,
    Block::CherryPlanks,
    Block::MangrovePlanks,
    Block::CraftingTable,
    Block::Furnace,
    Block::Chest,
    Block::Torch,
    Block::FurnitureWorkbench,
];

pub(super) const BLOCK_DEFS: &[BlockDef] = &[
    BlockDef {
        block: Block::Air,
        shape: RenderShape::Cube,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Replaceable],
        behavior: &behavior::INERT,
        flags: AIR_FLAGS,
        tiles: [Tile::OakLeaves, Tile::OakLeaves, Tile::OakLeaves],
        material: BlockMaterial::None,
        harvest_tier: 0,
        hardness: -1.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::Grass,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Terrain, BlockTag::Soil],
        // Dies back to dirt when smothered by a solid block (see `behavior::grass`).
        behavior: &behavior::GRASS,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::GrassTop, Tile::Dirt, Tile::GrassSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.7,
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Dirt,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::Dirt,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Terrain, BlockTag::Soil],
        // Greens over into grass when grass is nearby (see `behavior::dirt`).
        behavior: &behavior::DIRT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Dirt, Tile::Dirt, Tile::Dirt],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Dirt),
    },
    BlockDef {
        block: Block::Stone,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Stone, Tile::Stone, Tile::Stone],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        // Mined stone yields cobblestone (needs a wooden pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Cobblestone,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::Sand,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Terrain, BlockTag::Sand],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Sand, Tile::Sand, Tile::Sand],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Sand),
    },
    BlockDef {
        block: Block::Snow,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Terrain],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Snow, Tile::Dirt, Tile::GrassSnow],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Snow),
    },
    BlockDef {
        block: Block::Water,
        shape: RenderShape::Cube,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Replaceable],
        behavior: &behavior::WATER,
        flags: WATER_FLAGS,
        tiles: [Tile::Water, Tile::Water, Tile::Water],
        material: BlockMaterial::None,
        harvest_tier: 0,
        hardness: -1.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::OakLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::OakLogTop, Tile::OakLogTop, Tile::OakLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(OakLog),
    },
    BlockDef {
        block: Block::OakLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::OakLeaves, Tile::OakLeaves, Tile::OakLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(OakLeaves),
    },
    BlockDef {
        block: Block::SpruceLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::SpruceLogTop, Tile::SpruceLogTop, Tile::SpruceLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(SpruceLog),
    },
    BlockDef {
        block: Block::BirchLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::BirchLogTop, Tile::BirchLogTop, Tile::BirchLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(BirchLog),
    },
    BlockDef {
        block: Block::JungleLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::JungleLogTop, Tile::JungleLogTop, Tile::JungleLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(JungleLog),
    },
    BlockDef {
        block: Block::AcaciaLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::AcaciaLogTop, Tile::AcaciaLogTop, Tile::AcaciaLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(AcaciaLog),
    },
    BlockDef {
        block: Block::DarkOakLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::DarkOakLogTop,
            Tile::DarkOakLogTop,
            Tile::DarkOakLogSide,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(DarkOakLog),
    },
    BlockDef {
        block: Block::CherryLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CherryLogTop, Tile::CherryLogTop, Tile::CherryLogSide],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(CherryLog),
    },
    BlockDef {
        block: Block::MangroveLog,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Log],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::MangroveLogTop,
            Tile::MangroveLogTop,
            Tile::MangroveLogSide,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(MangroveLog),
    },
    BlockDef {
        block: Block::SpruceLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::SpruceLeaves, Tile::SpruceLeaves, Tile::SpruceLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(SpruceLeaves),
    },
    BlockDef {
        block: Block::BirchLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::BirchLeaves, Tile::BirchLeaves, Tile::BirchLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(BirchLeaves),
    },
    BlockDef {
        block: Block::JungleLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::JungleLeaves, Tile::JungleLeaves, Tile::JungleLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(JungleLeaves),
    },
    BlockDef {
        block: Block::AcaciaLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::AcaciaLeaves, Tile::AcaciaLeaves, Tile::AcaciaLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(AcaciaLeaves),
    },
    BlockDef {
        block: Block::DarkOakLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [
            Tile::DarkOakLeaves,
            Tile::DarkOakLeaves,
            Tile::DarkOakLeaves,
        ],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(DarkOakLeaves),
    },
    BlockDef {
        block: Block::MangroveLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [
            Tile::MangroveLeaves,
            Tile::MangroveLeaves,
            Tile::MangroveLeaves,
        ],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(MangroveLeaves),
    },
    BlockDef {
        block: Block::CherryLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::CherryLeaves, Tile::CherryLeaves, Tile::CherryLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(CherryLeaves),
    },
    BlockDef {
        block: Block::AzaleaLeaves,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Leaves, BlockTag::NoGrassDecay],
        behavior: &behavior::LEAVES,
        flags: LEAVES_FLAGS,
        tiles: [Tile::AzaleaLeaves, Tile::AzaleaLeaves, Tile::AzaleaLeaves],
        material: BlockMaterial::Foliage,
        harvest_tier: 0,
        hardness: 0.2,
        drop: drops_self!(AzaleaLeaves),
    },
    BlockDef {
        block: Block::RedSand,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[BlockTag::Sand],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::RedSand, Tile::RedSand, Tile::RedSand],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(RedSand),
    },
    BlockDef {
        block: Block::Sandstone,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::SandstoneTop,
            Tile::SandstoneBottom,
            Tile::SandstoneSide,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Sandstone),
    },
    BlockDef {
        block: Block::RedSandstone,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::RedSandstoneTop,
            Tile::RedSandstoneBottom,
            Tile::RedSandstoneSide,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(RedSandstone),
    },
    BlockDef {
        block: Block::Terracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Terracotta, Tile::Terracotta, Tile::Terracotta],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Terracotta),
    },
    BlockDef {
        block: Block::WhiteTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::WhiteTerracotta,
            Tile::WhiteTerracotta,
            Tile::WhiteTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(WhiteTerracotta),
    },
    BlockDef {
        block: Block::OrangeTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::OrangeTerracotta,
            Tile::OrangeTerracotta,
            Tile::OrangeTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(OrangeTerracotta),
    },
    BlockDef {
        block: Block::YellowTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::YellowTerracotta,
            Tile::YellowTerracotta,
            Tile::YellowTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(YellowTerracotta),
    },
    BlockDef {
        block: Block::BrownTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::BrownTerracotta,
            Tile::BrownTerracotta,
            Tile::BrownTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(BrownTerracotta),
    },
    BlockDef {
        block: Block::RedTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::RedTerracotta,
            Tile::RedTerracotta,
            Tile::RedTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(RedTerracotta),
    },
    BlockDef {
        block: Block::LightGrayTerracotta,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::LightGrayTerracotta,
            Tile::LightGrayTerracotta,
            Tile::LightGrayTerracotta,
        ],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(LightGrayTerracotta),
    },
    BlockDef {
        block: Block::Podzol,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PodzolTop, Tile::Dirt, Tile::PodzolSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Podzol),
    },
    BlockDef {
        block: Block::Mycelium,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MyceliumTop, Tile::Dirt, Tile::MyceliumSide],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Mycelium),
    },
    BlockDef {
        block: Block::CoarseDirt,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CoarseDirt, Tile::CoarseDirt, Tile::CoarseDirt],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(CoarseDirt),
    },
    BlockDef {
        block: Block::Gravel,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Gravel, Tile::Gravel, Tile::Gravel],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Gravel),
    },
    BlockDef {
        block: Block::Clay,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Clay, Tile::Clay, Tile::Clay],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Clay),
    },
    BlockDef {
        block: Block::Mud,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Mud, Tile::Mud, Tile::Mud],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(Mud),
    },
    BlockDef {
        block: Block::MossBlock,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MossBlock, Tile::MossBlock, Tile::MossBlock],
        material: BlockMaterial::Dirt,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(MossBlock),
    },
    BlockDef {
        block: Block::SnowBlock,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Snow, Tile::Snow, Tile::Snow],
        material: BlockMaterial::Sand,
        harvest_tier: 0,
        hardness: 0.5,
        drop: drops_self!(SnowBlock),
    },
    BlockDef {
        block: Block::PackedIce,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PackedIce, Tile::PackedIce, Tile::PackedIce],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 0.5,
        drop: drops_self!(PackedIce),
    },
    BlockDef {
        block: Block::Ice,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Ice, Tile::Ice, Tile::Ice],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 0.5,
        drop: drops_self!(Ice),
    },
    BlockDef {
        block: Block::Calcite,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Calcite, Tile::Calcite, Tile::Calcite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Calcite),
    },
    BlockDef {
        block: Block::Granite,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Granite, Tile::Granite, Tile::Granite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Granite),
    },
    BlockDef {
        block: Block::Diorite,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Diorite, Tile::Diorite, Tile::Diorite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Diorite),
    },
    BlockDef {
        block: Block::Andesite,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Andesite, Tile::Andesite, Tile::Andesite],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Andesite),
    },
    BlockDef {
        block: Block::Tuff,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Tuff, Tile::Tuff, Tile::Tuff],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 1.5,
        drop: drops_self!(Tuff),
    },
    BlockDef {
        block: Block::CoalOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CoalOre, Tile::CoalOre, Tile::CoalOre],
        material: BlockMaterial::Ore,
        harvest_tier: 1,
        hardness: 3.0,
        // Coal ore → one coal (wooden pickaxe or better).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Coal,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::IronOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::IronOre, Tile::IronOre, Tile::IronOre],
        material: BlockMaterial::Ore,
        harvest_tier: 2,
        hardness: 3.0,
        // Iron ore → one raw iron (needs a stone pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::RawIron,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::CopperOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CopperOre, Tile::CopperOre, Tile::CopperOre],
        material: BlockMaterial::Ore,
        harvest_tier: 2,
        hardness: 3.0,
        // Copper ore → 2–4 raw copper (needs a stone pickaxe).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::RawCopper,
                min: 2,
                max: 4,
            }],
        },
    },
    BlockDef {
        block: Block::GoldOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::GoldOre, Tile::GoldOre, Tile::GoldOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        // Gold ore → one raw gold (needs an iron pickaxe — see harvest_tier);
        // smelt the raw gold into a gold ingot.
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::RawGold,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::RedstoneOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::RedstoneOre, Tile::RedstoneOre, Tile::RedstoneOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        // Redstone ore drops nothing for now (redstone the item doesn't exist yet,
        // and this ore is slated for removal). Breaks like any ore; yields no item.
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::LapisOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::LapisOre, Tile::LapisOre, Tile::LapisOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        // Lapis ore → 2–4 lapis lazuli (needs an iron pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::LapisLazuli,
                min: 2,
                max: 4,
            }],
        },
    },
    BlockDef {
        block: Block::DiamondOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::DiamondOre, Tile::DiamondOre, Tile::DiamondOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        // Diamond ore → one diamond (needs an iron pickaxe — see harvest_tier).
        drop: DropSpec {
            drops: &[Drop {
                item: ItemType::Diamond,
                min: 1,
                max: 1,
            }],
        },
    },
    BlockDef {
        block: Block::EmeraldOre,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::EmeraldOre, Tile::EmeraldOre, Tile::EmeraldOre],
        material: BlockMaterial::Ore,
        harvest_tier: 3,
        hardness: 3.0,
        drop: drops_self!(EmeraldOre),
    },
    BlockDef {
        block: Block::Pumpkin,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::PumpkinTop, Tile::PumpkinTop, Tile::PumpkinSide],
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 1.0,
        drop: drops_self!(Pumpkin),
    },
    BlockDef {
        block: Block::Melon,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::MelonTop, Tile::MelonTop, Tile::MelonSide],
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 1.0,
        drop: drops_self!(Melon),
    },
    BlockDef {
        block: Block::Cactus,
        shape: RenderShape::Cube,
        collision: CACTUS_BOXES,
        emission: 0,
        // Fragile + roots in sand: it breaks when the sand beneath it is dug (like the
        // dead bush) and may only be placed on sandy ground. Non-opaque (see
        // CACTUS_FLAGS) so neighbours keep their faces toward the inset trunk.
        tags: &[BlockTag::Fragile, BlockTag::RootsInSand],
        behavior: &behavior::FRAGILE,
        flags: CACTUS_FLAGS,
        tiles: [Tile::CactusTop, Tile::CactusBottom, Tile::CactusSide],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.4,
        drop: drops_self!(Cactus),
    },
    BlockDef {
        block: Block::ShortGrass,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::Replaceable, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::ShortGrass, Tile::ShortGrass, Tile::ShortGrass],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: DropSpec::NONE,
    },
    BlockDef {
        block: Block::Fern,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::Replaceable, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::Fern, Tile::Fern, Tile::Fern],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Fern),
    },
    BlockDef {
        block: Block::Dandelion,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::Dandelion, Tile::Dandelion, Tile::Dandelion],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Dandelion),
    },
    BlockDef {
        block: Block::Poppy,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::Poppy, Tile::Poppy, Tile::Poppy],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Poppy),
    },
    BlockDef {
        block: Block::Cornflower,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::Cornflower, Tile::Cornflower, Tile::Cornflower],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Cornflower),
    },
    BlockDef {
        block: Block::Allium,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::Allium, Tile::Allium, Tile::Allium],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Allium),
    },
    BlockDef {
        block: Block::AzureBluet,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::AzureBluet, Tile::AzureBluet, Tile::AzureBluet],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(AzureBluet),
    },
    BlockDef {
        block: Block::OxeyeDaisy,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::OxeyeDaisy, Tile::OxeyeDaisy, Tile::OxeyeDaisy],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(OxeyeDaisy),
    },
    BlockDef {
        block: Block::RedTulip,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::RedTulip, Tile::RedTulip, Tile::RedTulip],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(RedTulip),
    },
    BlockDef {
        block: Block::DeadBush,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        tags: &[BlockTag::Fragile, BlockTag::Replaceable, BlockTag::RootsInSand],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::DeadBush, Tile::DeadBush, Tile::DeadBush],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(DeadBush),
    },
    BlockDef {
        block: Block::BrownMushroom,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        // Soil or any stone: grass/dirt or a BlockMaterial::Stone surface (see `can_root_on`).
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil, BlockTag::RootsInStone],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [
            Tile::BrownMushroom,
            Tile::BrownMushroom,
            Tile::BrownMushroom,
        ],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(BrownMushroom),
    },
    BlockDef {
        block: Block::RedMushroom,
        shape: RenderShape::Cross,
        collision: NO_BOXES,
        emission: 0,
        // Soil or any stone: grass/dirt or a BlockMaterial::Stone surface (see `can_root_on`).
        tags: &[BlockTag::Fragile, BlockTag::RootsInSoil, BlockTag::RootsInStone],
        behavior: &behavior::FRAGILE,
        flags: PLANT_FLAGS,
        tiles: [Tile::RedMushroom, Tile::RedMushroom, Tile::RedMushroom],
        material: BlockMaterial::Plant,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(RedMushroom),
    },
    // --- Crafting update: crafted/placeable blocks. ---
    BlockDef {
        block: Block::Cobblestone,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::Cobblestone, Tile::Cobblestone, Tile::Cobblestone],
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 2.0,
        drop: drops_self!(Cobblestone),
    },
    BlockDef {
        block: Block::OakPlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::OakPlanks, Tile::OakPlanks, Tile::OakPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(OakPlanks),
    },
    BlockDef {
        block: Block::SprucePlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::SprucePlanks, Tile::SprucePlanks, Tile::SprucePlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(SprucePlanks),
    },
    BlockDef {
        block: Block::BirchPlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::BirchPlanks, Tile::BirchPlanks, Tile::BirchPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(BirchPlanks),
    },
    BlockDef {
        block: Block::JunglePlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::JunglePlanks, Tile::JunglePlanks, Tile::JunglePlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(JunglePlanks),
    },
    BlockDef {
        block: Block::AcaciaPlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::AcaciaPlanks, Tile::AcaciaPlanks, Tile::AcaciaPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(AcaciaPlanks),
    },
    BlockDef {
        block: Block::DarkOakPlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::DarkOakPlanks,
            Tile::DarkOakPlanks,
            Tile::DarkOakPlanks,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(DarkOakPlanks),
    },
    BlockDef {
        block: Block::CherryPlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [Tile::CherryPlanks, Tile::CherryPlanks, Tile::CherryPlanks],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(CherryPlanks),
    },
    BlockDef {
        block: Block::MangrovePlanks,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        tiles: [
            Tile::MangrovePlanks,
            Tile::MangrovePlanks,
            Tile::MangrovePlanks,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.0,
        drop: drops_self!(MangrovePlanks),
    },
    BlockDef {
        block: Block::CraftingTable,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS,
        // [top, bottom, side]: the 3-tile model uses one side texture for all
        // four faces, so the recognizable front art is shown on every side.
        tiles: [
            Tile::CraftingTableTop,
            Tile::OakPlanks,
            Tile::CraftingTableFront,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.5,
        drop: drops_self!(CraftingTable),
    },
    BlockDef {
        block: Block::Furnace,
        shape: RenderShape::Cube,
        collision: FULL_CUBE_BOXES,
        emission: 28,
        tags: &[],
        behavior: &behavior::INERT,
        flags: FULL_CUBE_FLAGS.with(BlockFlags::DIRECTIONAL_VIEW),
        // [top, bottom, side]: the placed furnace is meshed directionally (front on
        // the facing face, `furnace_side` on the others — see mesh::builder), so the
        // default side is `furnace_side`. The inventory/held item cube puts the
        // front on one visible face via `render::block_model::block_icon_faces`.
        tiles: [Tile::FurnaceTop, Tile::FurnaceTop, Tile::FurnaceSide],
        // Stone material → needs at least a wooden pickaxe to harvest.
        material: BlockMaterial::Stone,
        harvest_tier: 1,
        hardness: 3.5,
        drop: drops_self!(Furnace),
    },
    BlockDef {
        block: Block::Chest,
        shape: RenderShape::Cube,
        collision: CHEST_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        // SOLID but non-opaque: the placed chest is drawn as a custom inset body +
        // hinged lid (the mesher skips its cell — see render::chest_model), so
        // neighbours keep their faces toward it and it casts no full-cube shadow.
        flags: CHEST_FLAGS.with(BlockFlags::DIRECTIONAL_VIEW),
        // [top, bottom, side] feeds only the inventory/held icon now (the placed block
        // is drawn from its own model). The icon overrides the front face via
        // render::block_model::block_icon_faces. Bottom reuses the side tile (the
        // vanilla chest bottom is unpainted and never visible).
        tiles: [Tile::ChestTop, Tile::ChestSide, Tile::ChestSide],
        // Wood → hand-harvestable (no pickaxe needed), like planks/crafting table.
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.5,
        drop: drops_self!(Chest),
    },
    BlockDef {
        block: Block::Torch,
        shape: RenderShape::Torch,
        collision: NO_BOXES,
        emission: 28,
        tags: &[BlockTag::Fragile],
        behavior: &behavior::FRAGILE,
        flags: TORCH_FLAGS,
        // [top, bottom, side]: the in-world pole (see mesh::torch) caps the top with
        // the flame tile and wraps the four thin sides with the center-strip body;
        // the bottom reuses the strip (it sits against the support and is unseen).
        // The inventory icon / held item use the full `Tile::Torch` sprite instead
        // (see ItemType::render_kind), so these per-face tiles only feed the model.
        tiles: [Tile::TorchTop, Tile::TorchSide, Tile::TorchSide],
        // Manufactured object, not a plant: instant to break, hand-harvestable,
        // drops itself. `Other` keeps it out of the tool-gated Stone/Ore set.
        material: BlockMaterial::Other,
        harvest_tier: 0,
        hardness: 0.0,
        drop: drops_self!(Torch),
    },
    BlockDef {
        block: Block::FurnitureWorkbench,
        // The first data-driven Blockbench block: chunk-meshed from its `.bbmodel`
        // (geometry/texture/collision/selection all baked from the model, multi-cell
        // footprint auto-split — see `block_model`), not the atlas.
        shape: RenderShape::Model(BlockModelKind::FurnitureWorkbench),
        // Collision is model-driven per cell — `Block::collision_boxes` / `World::
        // collision_boxes_at` read it from the model, never this field.
        collision: NO_BOXES,
        emission: 0,
        tags: &[],
        behavior: &behavior::INERT,
        flags: MODEL_FLAGS.with(BlockFlags::DIRECTIONAL_VIEW),
        // [top, bottom, side] feeds only the inventory/held icon for now (the placed
        // block draws from its model); reuse the crafting-table art as a stand-in.
        tiles: [
            Tile::CraftingTableTop,
            Tile::OakPlanks,
            Tile::CraftingTableFront,
        ],
        material: BlockMaterial::Wood,
        harvest_tier: 0,
        hardness: 2.5,
        drop: drops_self!(FurnitureWorkbench),
    },
];

impl RegistryKey for Block {
    #[inline]
    fn to_id(self) -> u8 {
        self.id()
    }
}

impl TableEntry for BlockDef {
    type Key = Block;
    #[inline]
    fn key(&self) -> Block {
        self.block
    }
}

#[inline]
pub(super) fn from_id(id: u8) -> Block {
    registry::from_id(BLOCK_DEFS, id, Block::Air)
}

#[inline]
pub(super) fn def(block: Block) -> &'static BlockDef {
    registry::def(BLOCK_DEFS, block)
}
