// Texture transitions: a displacement mask picks one material per texel near
// a face's edges, without averaging albedos. `TRANSITION_SET` and
// `TRANSITION_FACES` are generated by the pipeline from the catalog.

const TRANSITION_MASK_SIDE: i32 = 4;
const TRANSITION_MASK_TEXELS: i32 = 16 * TRANSITION_MASK_SIDE;

// The mesher's payload: nine 4-bit material slots (source, then eight
// in-plane neighbours) across the lanes a plain face no longer needs, and a
// set id split between the UV mode's low bits and the shade lane.
struct TransitionWords {
    lo: u32,
    hi: u32,
    set_id: u32,
}

fn transition_words(packed: u32, packed2: u32) -> TransitionWords {
    let lo = (packed & 0x7FFu) | (((packed >> 26u) & 0x1u) << 11u)
        | ((packed >> 31u) << 12u) | (((packed2 >> 6u) & 0x3FFu) << 13u)
        | (((packed2 >> 19u) & 0x1FFu) << 23u);
    let set_id = (((packed >> 23u) & 0x7u) - UV_MODE_TRANSITION) | (((packed >> 13u) & 0x3u) << 2u);
    return TransitionWords(lo, packed2 >> 28u, set_id);
}

fn transition_plane(p: vec3<f32>, normal: u32) -> vec2<f32> {
    switch normal {
        case NORMAL_POS_X: { return vec2<f32>(-p.z, -p.y); }
        case NORMAL_NEG_X: { return vec2<f32>( p.z, -p.y); }
        case NORMAL_POS_Y: { return vec2<f32>( p.x,  p.z); }
        case NORMAL_NEG_Y: { return vec2<f32>( p.x, -p.z); }
        case NORMAL_POS_Z: { return vec2<f32>( p.x, -p.y); }
        default: { return vec2<f32>(-p.x, -p.y); }
    }
}

struct TransitionSample {
    material: u32,
    donor_offset: vec2<i32>,
}

fn transition_owner(in: VsOut, style: vec4<u32>) -> TransitionSample {
    let own = in.layer & 15u;
    let original = TransitionSample(own, vec2<i32>(0));
    let radius = f32(style.y) / 16.0;
    let uv = (floor(in.uv * 16.0) + vec2<f32>(0.5)) / 16.0;
    if (all(uv >= vec2<f32>(radius)) && all(uv <= vec2<f32>(1.0 - radius))) { return original; }
    // Keeping the large origin out of the floating-point sum preserves the
    // mask phase when the renderer rebases, including negative coordinates.
    let p = in.view + u.cam_pos.xyz + vec3<f32>(u.render_origin.xyz % vec3<i32>(TRANSITION_MASK_TEXELS));
    let pixel = vec2<i32>(floor(transition_plane(p, in.ncode) * 16.0));
    // A power-of-two mask wraps negative coordinates without signed remainders.
    let wrapped = pixel & vec2<i32>(TRANSITION_MASK_TEXELS - 1);
    let cell = wrapped / vec2<i32>(16);
    let mask = textureLoad(atlas, wrapped % vec2<i32>(16),
        i32(style.x) + cell.y * TRANSITION_MASK_SIDE + cell.x, 0);
    // Disk-distributed texel offsets give a gradual change in pixel density
    // and rounded corners without introducing intermediate albedo colours.
    let displacement = (mask.rg * 2.0 - vec2<f32>(1.0)) * radius;
    let offset = vec2<i32>(floor(uv + displacement));
    if (all(offset == vec2<i32>(0))) { return original; }
    let grid = (offset.y + 1) * 3 + offset.x + 1;
    let index = u32(select(grid, grid + 1, grid < 4));
    var donor: u32;
    if (index == 8u) { donor = in.overlay_layer & 15u; }
    else { donor = (in.layer >> (index * 4u)) & 15u; }
    if (donor == 0u || donor == own) { return original; }
    return TransitionSample(donor, offset);
}

fn transition_albedo(in: VsOut, grad_x: vec2<f32>, grad_y: vec2<f32>) -> vec3<f32> {
    let style = TRANSITION_SET[in.overlay_layer >> 4u];
    let owner = transition_owner(in, style);
    var face = 2u;
    if (in.ncode == NORMAL_POS_Y) { face = 0u; }
    if (in.ncode == NORMAL_NEG_Y) { face = 1u; }
    let material = TRANSITION_FACES[style.w + owner.material * 3u + face];
    let layer = terrain_variant_layer(in, material.x, owner.donor_offset);
    let tex = textureSampleGrad(atlas, samp, in.uv, i32(layer), grad_x, grad_y);
    var rgb = tex.rgb;
    if ((material.z & 1u) != 0u) { rgb *= in.tint; }
    if ((material.z & 2u) != 0u) {
        // Side overlays are vertically anchored (grass at the block's top).
        // Extend the donor's adjoining edge instead of repeating its top fringe
        // on the block below. The base material remains freely tileable.
        var overlay_uv = in.uv;
        if (owner.donor_offset.y != 0) {
            overlay_uv.y = clamp(in.uv.y - f32(owner.donor_offset.y), 0.5 / 16.0, 15.5 / 16.0);
        }
        let overlay_layer = terrain_variant_layer(in, material.y, owner.donor_offset);
        let overlay = textureSampleGrad(atlas, samp, overlay_uv, i32(overlay_layer), grad_x, grad_y);
        var color = overlay.rgb;
        if ((material.z & 4u) != 0u) { color *= in.tint; }
        rgb = mix(rgb, color, overlay.a);
    }
    return rgb;
}
