// Per-cell static tile variation. `spatial_hash` and `block_variation_count`
// are generated by the pipeline from the registry.

fn variation_cell(local_pos: vec3<f32>, origin: vec3<i32>, normal: vec3<f32>) -> vec3<i32> {
    // Step inside the face before flooring, and add the large origin as integers.
    return vec3<i32>(floor(local_pos - normal * (1.0 / 64.0))) + origin;
}

fn variation_donor_offset(offset: vec2<i32>, normal: u32) -> vec3<i32> {
    switch normal {
        case NORMAL_POS_X: { return vec3<i32>(0, -offset.y, -offset.x); }
        case NORMAL_NEG_X: { return vec3<i32>(0, -offset.y, offset.x); }
        case NORMAL_POS_Y: { return vec3<i32>(offset.x, 0, offset.y); }
        case NORMAL_NEG_Y: { return vec3<i32>(offset.x, 0, -offset.y); }
        case NORMAL_POS_Z: { return vec3<i32>(offset.x, -offset.y, 0); }
        default: { return vec3<i32>(-offset.x, -offset.y, 0); }
    }
}

// Base layers and their dyed twins are the atlas's only two families.
fn variation_count(layer: u32, tile_count: u32) -> u32 {
    return block_variation_count(select(layer, layer - tile_count, layer >= tile_count));
}

fn block_variant_layer(layer: u32, cell: vec3<i32>, tile_count: u32) -> u32 {
    // Dyed layers use the same selection in their parallel atlas family.
    let count = variation_count(layer, tile_count);
    if (count <= 1u) { return layer; }
    return layer + spatial_hash(cell, 0u) % count;
}
